#!/usr/bin/env node

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import type { TgFrameworkConfig } from './types/cli-config';

async function main() {
  const cwd = process.cwd();
  const configPath = resolve(cwd, 'tg-framework.config.js');

  let config: TgFrameworkConfig;
  try {
    const module = await import(pathToFileURL(configPath).href);
    config = module.default;
  } catch {
    console.error(`Error: could not load config at ${configPath}`);
    process.exit(1);
  }

  const localeFile = resolve(cwd, config.localesDir, `${config.defaultLocale}.txt`);

  let content: string;
  try {
    content = readFileSync(localeFile, 'utf-8');
  } catch {
    console.error(`Error: could not read locale file at ${localeFile}`);
    process.exit(1);
  }

  const entries: { key: string; text: string }[] = [];
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    const text = trimmed.slice(eqIndex + 1).trim();
    if (key) {
      entries.push({ key, text });
    }
  }

  const argRegex = /\$\{(\w+)\}/g;
  let hasArgs = false;
  const parsed = entries.map(({ key, text }) => {
    const args: string[] = [];
    let match: RegExpExecArray | null;
    while ((match = argRegex.exec(text)) !== null) {
      args.push(match[1]);
    }
    if (args.length > 0) hasArgs = true;
    return { key, text, args };
  });

  const lines = ['// This file is auto-generated by tg-framework. Do not edit manually.', ''];
  if (hasArgs) {
    lines.push('type ArgValue = string | number;', '');
  }
  lines.push('export type LocaleKeysType = {');
  for (const { key, text, args } of parsed) {
    const escapedText = text.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    if (args.length > 0) {
      const argsObj = args.map((a) => `${a}: ArgValue`).join('; ');
      lines.push(`  "${key}": { text: "${escapedText}"; args: { ${argsObj} } };`);
    } else {
      lines.push(`  "${key}": { text: "${escapedText}"; args: undefined };`);
    }
  }
  lines.push('};', '');

  lines.push(`
export type LocaleKeys = keyof LocaleKeysType;

export type LocaleArgs<Key extends LocaleKeys> = LocaleKeysType[Key]['args'];`);

  const outputDir = resolve(cwd, config.outputDir);
  mkdirSync(outputDir, { recursive: true });

  const outputFile = join(outputDir, 'locale-types.ts');
  writeFileSync(outputFile, lines.join('\n'), 'utf-8');

  console.log(`Generated ${outputFile}`);
}

main();
